// <auto-generated />
using System;
using DateAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DateAccess.Migrations
{
    [DbContext(typeof(CinemaDbContext))]
    [Migration("20231203222505_InitDb")]
    partial class InitDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DateAccess.Models.Ganre", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"));

                    b.Property<string>("GanreName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Ganres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GanreName = "Бойовик"
                        },
                        new
                        {
                            Id = 2,
                            GanreName = "Пригоди"
                        },
                        new
                        {
                            Id = 3,
                            GanreName = "Історичний"
                        },
                        new
                        {
                            Id = 4,
                            GanreName = "Драма"
                        },
                        new
                        {
                            Id = 5,
                            GanreName = "Жахи"
                        });
                });

            modelBuilder.Entity("DateAccess.Models.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "У розпал Другої світової війни полковник США Леслі Гровс призначає блискучого фізика-теоретика Роберта Оппенгеймера науковим керівником Манхеттенського проєкту. Вся індустріальна міць та інноваційні технології країни йдуть на те, щоб випередити нацистську Німеччину у створенні зброї масового знищення на основі розщеплення ядра атома. Оппенгеймер проводить успішні випробування першої у світі ядерної бомби, що дозволяє наблизити перемогу у війні. Проте чоловіка мучать докори совісті, оскільки його винахід здатний призвести до знищення всього людства...",
                            ImagePath = "https://uaserials.pro/posters/8215.jpg",
                            Title = "Оппенгеймер"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Події розгортаються у майбутньому, під час війни між людьми та штучним інтелектом. Колишній спецпризначенець Джошуа разом із загоном оперативників отримує завдання знайти та вбити архітектора просунутого штучного інтелекту — Творця, який розробив зброю, здатну покласти край не лише війні, а й усьому людству...",
                            ImagePath = "https://uaserials.pro/posters/8224.jpg",
                            Title = "Творець"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Висококласний найманий убивця, схильний до мізантропічного філософування, чекає на жертву в Парижі. Коли все йде не за планом, він сам ризикує перетворитися на ціль і вирушає розбиратися зі своїми замовниками...",
                            ImagePath = "https://uaserials.pro/posters/8216.jpg",
                            Title = "Вбивця"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Дія відбувається в 1947 році напередодні Хелловіну у Венеції, куди переїхав знаменитий детектив Еркюль Пуаро, що вийшов на пенсію. На прохання свого старого знайомого він неохоче відвідує спіритичний сеанс самопроголошеного медіума Джойс Рейнольдс, яку потрібно викрити як шахрайку. Незабаром після сеансу жінка-медіум трагічно гине, що змушує гостей, які зібралися в особняку, повірити в існування злих духів. Проте Пуаро переконаний, що сталося сплановане вбивство, яке йому належить розкрити.",
                            ImagePath = "https://uaserials.pro/posters/8174.jpg",
                            Title = "Привиди у Венеції"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Американський секретний агент Ітан Гант, що очолює оперативну групу «Місія нездійсненна», цього разу стикається з майже невразливим ворогом: штучним інтелектом під назвою «Сутність», що вийшов з-під контролю. Єдиний спосіб перемогти розумну технологію, яка загрожує всьому людству — знайти дві половинки таємничого ключа і розгадати їх секрет. Головний герой та його команда знову повинні кинути виклик смерті та подолати межу власних можливостей, щоб урятувати весь світ від загрози знищення...",
                            ImagePath = "https://uaserials.pro/posters/8127.jpg",
                            Title = "Місія нездійсненна: Розплата. Частина перша"
                        },
                        new
                        {
                            Id = 6,
                            Description = "У Тіхуані урядовий агент відвідує старого друга Ніка Фальконе, який уже вийшов на пенсію, і просить його повернутися у стрій. Нік має виконати усунути три цілі, які вважаються небезпечними для національної безпеки США. Тим часом агент Управління боротьби з наркотиками Ентоні Ван Овен дізнається, що за вбивством Февзі Полата, відомого через зв'язки із великими злочинними угрупованнями, стоїть Нік. Вийшовши на слід досвідченого агента, Ентоні поєднується з Ніком, щоб зупинити могутнього кримінального ватажка від використання інноваційного пристрою, здатного повністю відключити електроенергію в мегаполісі.",
                            ImagePath = "https://uaserials.pro/posters/8202.jpg",
                            Title = "Чорна мітка"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Лора Еш, беручи участь у викраденні коштовностей, обманює спільників і тікає до Парижа. Там вона стикається зі схожою на неї дівчиною, яка вчиняє самогубство. Лора вирішує скористатися ситуацією і видати загиблу за себе, а себе — за неї. Їй це вдається, але через сім років вона повертається до Парижа під ім'ям Лілі Воттс, вже як дружина нового посла США у Франції. Однак її колишні спільники продовжують пошуки вкрадених коштовностей...",
                            ImagePath = "https://uaserials.pro/posters/8237.jpg",
                            Title = "Фатальна жінка"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Тесляр Серджіо та колишня співачка Сабріна закохані одне в одне, але не можуть кинути своїх партнерів через фінансову залежність. Проте ситуація різко змінюється, коли колеги переконують чоловіка, що він виграв три мільйони євро в лотерею. Серджіо одразу ж кидає старе життя та тягне за собою не тільки Сабріну, а й усіх родичів. Коли пара дізнається, що жодного виграшу немає, вони вирішують продовжити брехати своїм сім'ям і вирушають разом з ними в незвичайну подорож Італією. Однак таємне завжди стає явним...",
                            ImagePath = "https://uaserials.pro/posters/8239.jpg",
                            Title = "Фантазери"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Цього року Стелла закінчує школу. У той час, коли подруги сидять за підручниками, батько йде до іншої, а мати на порозі депресії, Стелла відкриває для себе клубне життя 80-х і шалені нічні тусовки.",
                            ImagePath = "https://uaserials.pro/posters/8201.jpg",
                            Title = "Стелла в Парижі"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Подружня пара Стіне та Тейт разом зі своїм маленьким сином Немо вирішує втекти з Копенгагена, щоб сховатися у віддаленій хатині у безкраїх лісах Швеції, бажаючи налагодити стосунки та знайти спокій. Жінка прагне подолати творчу кризу та закінчити свій перший роман, а чоловік має намір задокументувати їхню «пригоду» у серії подкастів. Перебуваючи в повній ізоляції від зовнішнього світу, подружжя стикається з низкою дивних подій і зустрічає таємничих незнайомців, які неймовірно схожі на них самих...",
                            ImagePath = "https://uaserials.pro/posters/8221.jpg",
                            Title = "Ілюзія втечі"
                        });
                });

            modelBuilder.Entity("DateAccess.Models.MovieGanre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GanreId")
                        .HasColumnType("int");

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GanreId");

                    b.HasIndex("MovieId");

                    b.ToTable("MovieGanres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GanreId = 1,
                            MovieId = 1
                        },
                        new
                        {
                            Id = 2,
                            GanreId = 2,
                            MovieId = 2
                        },
                        new
                        {
                            Id = 3,
                            GanreId = 1,
                            MovieId = 3
                        },
                        new
                        {
                            Id = 4,
                            GanreId = 2,
                            MovieId = 4
                        },
                        new
                        {
                            Id = 5,
                            GanreId = 5,
                            MovieId = 5
                        },
                        new
                        {
                            Id = 6,
                            GanreId = 1,
                            MovieId = 6
                        },
                        new
                        {
                            Id = 7,
                            GanreId = 2,
                            MovieId = 7
                        },
                        new
                        {
                            Id = 9,
                            GanreId = 4,
                            MovieId = 9
                        },
                        new
                        {
                            Id = 10,
                            GanreId = 5,
                            MovieId = 10
                        });
                });

            modelBuilder.Entity("DateAccess.Models.MovieGanre", b =>
                {
                    b.HasOne("DateAccess.Models.Ganre", null)
                        .WithMany("Movies")
                        .HasForeignKey("GanreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DateAccess.Models.Movie", null)
                        .WithMany("Ganres")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DateAccess.Models.Ganre", b =>
                {
                    b.Navigation("Movies");
                });

            modelBuilder.Entity("DateAccess.Models.Movie", b =>
                {
                    b.Navigation("Ganres");
                });
#pragma warning restore 612, 618
        }
    }
}
